added Film and User Data class, Film and User controllers, tests
Luz1634/java-filmorate pull request #2
Opened 2023-04-23 20:14 UTC by Luz1634

2023-04-25 05:12 UTC, z8q requested changes

2023-04-25 05:12 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            return false;
В дальнейшем, тут можно бросить исключение и обрабатывать через ExceptionHandler:
https://www.baeldung.com/exception-handling-for-rest-with-spring
Это пока больше для информации, но если есть желание, можно применить)

2023-04-25 05:12 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return ResponseEntity.badRequest().body(film);
Можно попробовать создать класс, в котором было бы поле для описания ошибки. И возвращать его экземпляр с нужным описанием

2023-04-25 05:12 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private Map<Integer, Film> films = new HashMap<>();
Мапы тут и в UserController стоит сделать final

2023-04-25 05:12 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            if (user.getEmail().isBlank() || !user.getEmail().contains("@")) {
Если передадим поле так: "email": "useryandex.ru@",
то программа примет это как верное написание почты

2023-04-25 05:12 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            if (user.getLogin().isBlank() || user.getLogin().contains(" ")) {
isBlank проверяет на наличие пробелов тоже.
.contains(" ") не нужен

2023-10-06 21:51 UTC, Luz1634 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            if (user.getLogin().isBlank() || user.getLogin().contains(" ")) {
contains(" ") нужен для проверки пробелов внутри логина

2023-10-06 21:55 UTC, Luz1634 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            if (user.getEmail().isBlank() || !user.getEmail().contains("@")) {
Это простая валидация указанная в ТЗ. В следующем спринте планирую её обновить вместе с добавлением @ExceptionHandler

2023-10-06 22:04 UTC, Luz1634 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return ResponseEntity.badRequest().body(film);
Мне нравиться идея с новым классом для описания ошибки, но я ориентировался на тесты Postman которые идут вместе с ТЗ. Как я понял, в них должен возвращаться сам объект User или Film для правильной проверки

2023-10-07 10:35 UTC, z8q approved these changes

2023-10-07 21:36 UTC, merged