ТЗ 11
Luz1634/java-filmorate pull request #4
Opened 2023-11-20 08:03 UTC by Luz1634

2023-11-20 19:37 UTC, z8q requested changes

2023-11-20 19:37 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      public Film addFilm(Film film) {
Допускается добавление дублей фильмов. Стоит сделать проверки по каким-нибудь ключевым полям

2023-11-20 19:37 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      public Film addFilm(Film film) {
При добавлении фильма с пропущенным id в mpa возникает ошибка, но фильм все равно сохраняется в базу.
POST http://localhost:8080/films
```JSON
{
	"name": "Die Hard",
	"description": "Action movie with Br-s Wil-s",
	"releaseDate": "1988-07-22",
	"rating": 100,
	"duration": 1,
	"mpa": {
		"id": 1,
		"name":"NC-17",
		"description": "17+"
	},
	"genres": [
		{
			"name": "action"
		},
		{
			"id": 2,
			"name": "drama"
		},
		{
			"id": 3,
			"name": "comedy"
		}
	]
}
```
У жанра с именем action нет id.
Получим такой ответ:
```JSON
{
	"timestamp": "2023-11-20T19:04:30.874+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/films"
}
```
А GET http://localhost:8080/films/ при этом вернет:
```JSON
[
	{
		"id": 1,
		"name": "Die Hard",
		"description": "Action movie with Br-s Wil-s",
		"releaseDate": "1988-07-22",
		"duration": 1,
		"mpa": {
			"id": 1,
			"name": "G"
		},
		"genres": [],
		"userLikes": []
	}
]
```

2023-11-20 19:37 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>      public User addUser(User user) {
Допускается добавление дублей пользователей.
Можно имя с логином проверять на уникальность

2023-11-20 19:37 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>      public User addUser(User user) {
При выполнении updateUser допускается сохранить пользователя с пустыми email. 
На логин валидация срабатывает

2023-11-20 19:37 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      public Film updateFilm(Film film) {
При update, если не укажу значение для поля name, то приходит понятная ошибка
```JSON
{
	"message": "Ошибка при валидации объекта",
	"exception": "[Название фильма пустое или null]"
}
```
Если попытаюсь сохранить пустое поле "releaseDate": "", то будет ошибка:
```JSON
{
	"timestamp": "2023-11-20T19:17:44.939+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/films"
}
```
Хотя  в логах появляется иинформация:
JdbcSQLIntegrityConstraintViolationException: NULL not allowed for column "RELEASE_DATE"

2023-11-20 19:37 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    private GenreStorage genreStorage;
final)

2023-11-20 19:37 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      @Email(message = "Не правильный email")
Нужен еще будет NotBblank

2023-11-21 02:13 UTC, Luz1634 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      public Film addFilm(Film film) {
Добавил проверку по названию для дублей при добавлении нового фильма.
Добавил новые аннотации для валидации на проверку id у mpa и genres. Теперь mpa и genres с id не входящими в указанные промежутки выдадут исключение. По ТЗ, при получении фильмов, для mpa и жанров достаточно передавать их id

2023-11-21 02:16 UTC, Luz1634 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>      public User addUser(User user) {
Добавил проверку по email и логину для дублей. Добавил недостающих аннотаций

2023-11-21 15:25 UTC, z8q approved these changes

2023-11-27 16:53 UTC, merged